### PR TITLE
Add a fpm-alpine Dockerfile

### PR DESCRIPTION
**Pull request by Baldinof**

### CODE REVIEW

**Comment by remialvado** [comment]
Ce sera pour quel type de projet ? Les pipeline ? Ou c'est la base pour nos images PHP+Apache ?

**Comment by smaftoul** [comment]
it's missing plenty of stuff from our apache image, is this normal ?
@remialvado pipelines are not running with fpm and a web server, it's for our web apps.

**Comment by Baldinof** [comment]
Yes, let's start with the bare minimum: php & mongo, Symfony 4 seems to work well with this image.

**Comment by remialvado** [comment]
@smaftoul : yes, this is why it looked weird to me at first. But @Baldinof explained me that this is juste a PHP-FPM with Caddy as a proxy. I like that even if it means 2 processus in one container (Caddy + FPM)

**Review by smaftoul — APPROVED** [review]

**Comment by smaftoul** [comment]
You can still add labels (http://label-schema.org/rc1/)

**Pull request merged**
